# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install codecov
    - pip install coverage

# command to run tests, e.g. python setup.py test
script:
    - coverage run --source remath setup.py test
after_success:
    - codecov
